workflows:
  default-workflow:
    name: Build Android Pulita
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      vars:
        FLUTTER_MIN_SDK_VERSION: "23"
    scripts:
      - name: Generazione Android Pulita
        script: |
          # 1. Rimuove e rigenera la cartella android con il nome corretto
          rm -rf android
          flutter create . --platforms=android --org com.flolk --project-name flolk
          
          # 2. Forzatura delle proprietà SDK per compatibilità plugin
          echo "Forzo le proprietà di sistema..."
          mkdir -p ~/.gradle
          cat << 'EOF' > ~/.gradle/init.gradle
          allprojects { project ->
              def forceSdk = {
                  if (project.extensions.findByName("android") != null) {
                      project.android.compileSdkVersion = 36
                  }
              }
              if (project.state.executed) {
                  forceSdk()
              } else {
                  project.afterEvaluate {
                      forceSdk()
                  }
              }
          }
          EOF
      - name: Generazione Icona e Nome App
        script: |
          flutter pub get
          flutter pub run flutter_launcher_icons
      - name: Build APK Release
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
