// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuR6hSvkHwYVg2NkiMNllfQ3818TBuOMw',
    appId: '1:307018377597:web:e94d6f5bc280dd4819c414',
    messagingSenderId: '307018377597',
    projectId: 'chat-30743',
    authDomain: 'chat-30743.firebaseapp.com',
    storageBucket: 'chat-30743.firebasestorage.app',
    measurementId: 'G-FEP1ENE9Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx-6nO3MyQsQZ5FAOQXXB4nhbpLyIju4U',
    appId: '1:307018377597:android:a7ab2cf1e25d373c19c414',
    messagingSenderId: '307018377597',
    projectId: 'chat-30743',
    storageBucket: 'chat-30743.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAXHMGdXANqRCNA1ZDs5JnT4hiWfaMA4A',
    appId: '1:307018377597:ios:cbb6c30fc8e739e519c414',
    messagingSenderId: '307018377597',
    projectId: 'chat-30743',
    storageBucket: 'chat-30743.firebasestorage.app',
    iosBundleId: 'com.example.secureChatApp',
  );
}
